# Generated by Django 5.1.4 on 2024-12-06 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='user_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя пользователя')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('password', models.CharField(max_length=50, verbose_name='Имя пользователя')),
                ('description', models.DateField(verbose_name='Дата Рождения')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('patronymic', models.CharField(max_length=50, verbose_name='Отчетство')),
                ('delivery_adress', models.CharField(max_length=150, verbose_name='Адрес доставки')),
                ('inn_ur', models.CharField(max_length=10, verbose_name='ИНН юр. лица')),
                ('inn_fiz', models.CharField(max_length=12, verbose_name='ИНН физ. лица')),
            ],
        ),
        migrations.CreateModel(
            name='sell_items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('shop_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats_office.shop', verbose_name='Магазин')),
            ],
        ),
        migrations.AddField(
            model_name='shop',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='stats_office.user_data', verbose_name='Владелец магазина'),
        ),
    ]
