# Generated by Django 5.1.4 on 2024-12-07 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats_office', '0002_alter_sell_items_description_alter_sell_items_name_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='sells',
            new_name='sell',
        ),
        migrations.RenameModel(
            old_name='sell_items',
            new_name='sell_item',
        ),
        migrations.RenameModel(
            old_name='shops',
            new_name='shop',
        ),
        migrations.AlterField(
            model_name='user_data',
            name='password',
            field=models.CharField(max_length=50, verbose_name='пароль'),
        ),
    ]
