# Generated by Django 5.1.4 on 2024-12-09 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats_office', '0004_remove_sell_shop_id_sell_item_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_data',
            name='delivery_adress',
        ),
        migrations.RemoveField(
            model_name='user_data',
            name='description',
        ),
        migrations.RemoveField(
            model_name='user_data',
            name='email',
        ),
        migrations.RemoveField(
            model_name='user_data',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user_data',
            name='inn_fiz',
        ),
        migrations.RemoveField(
            model_name='user_data',
            name='inn_ur',
        ),
        migrations.RemoveField(
            model_name='user_data',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='user_data',
            name='password',
        ),
        migrations.RemoveField(
            model_name='user_data',
            name='patronymic',
        ),
        migrations.AlterField(
            model_name='sell_item',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='фотография'),
        ),
    ]
